export interface IColor extends Array<number> { 
    0: number,
    1: number,
    2: number,
    length: 3
}

export let black : IColor = [10, 10, 10]
export let white : IColor = [255, 255, 255]
export let blue : IColor = [0, 204, 255]
export let orange : IColor = [255, 127, 0]
export let green : IColor = [0, 204, 0]
export let yellow : IColor = [255, 177, 0]
export let red : IColor = [204, 0, 0]
export let dark_gray : IColor = [64, 64, 64]
export let gray : IColor = [102, 102, 102]
export let purple : IColor = [138,43,226]
export let light_cyan : IColor = [224, 255, 255]
export let charcoal : IColor = [52, 40, 44]
export let charcoal_complement : IColor = [39, 51, 47]
export let violet : IColor = [238, 130, 238]
export let indigo : IColor = [75, 0, 130]
export let goldenrod : IColor = [218, 165, 32]
export let dark_slate_gray : IColor = [47, 79, 79]
export let light_slate_gray : IColor = [119, 136, 153]
export let dark_red : IColor = [139, 0, 0]
export let firebrick : IColor = [178, 34, 34]
export let midnight_blue : IColor = [25, 25, 112]
export let hero_blue : IColor = [0, 207, 255]

export let normal : IColor = [150, 150, 150]
export let bg_remote_vision : IColor = [51, 102, 153]

export let target_path = yellow
export let target_cursor = orange
export let target_error = red
export let bg_unexplored = charcoal
export let bg_memory = charcoal_complement
export let memory = dark_gray
export let damage_flash = red
export let power_booster = orange
export let power_shield = green
export let power_cloak  = yellow
export let power_phasewalk  = violet
export let power_hack = hero_blue
export let power_axe = goldenrod
export let power_warp = firebrick

export let color_force = orange
export let color_stun = violet
export let color_explosion = damage_flash

export let color_notes_player = white

export let forest_green : IColor = [34, 139, 34]


//#####  Color Palette by Paletton.com
//#####  Palette URL: http://paletton.com/#uid=30x0u0kllllaFw0g0qFqFg0w0aF
// *** Primary color:

export let primary_shade_0 = [170,111, 57]
export let primary_shade_1 = [255,211,170]
export let primary_shade_2 = [212,157,106]
export let primary_shade_3 = [128, 72, 21]
export let primary_shade_4 = [ 85, 41,  0]

// *** Secondary color (1):

export let secondary_blue_shade_0 = [ 47, 64,115]
export let secondary_blue_shade_1 = [121,134,172]
export let secondary_blue_shade_2 = [ 80, 96,143]
export let secondary_blue_shade_3 = [ 22, 38, 86]
export let secondary_blue_shade_4 = [  6, 19, 57]

// *** Secondary color (2):

export let secondary_green_shade_0 = [ 43,130, 58]
export let secondary_green_shade_1 = [130,195,141]
export let secondary_green_shade_2 = [ 81,163, 95]
export let secondary_green_shade_3 = [ 16, 98, 30]
export let secondary_green_shade_4 = [  0, 65, 11]

// #####  Generated by Paletton.com (c) 2002-2014

export let monster_color = [255, 255, 0]